config/routes.rb
Rails.application.routes.draw do
  resources :images
  root 'pages#home'
  get 'friends', to: "users#friends"
  get 'arthour', to: 'pages#arthour'
  get 'about', to: 'pages#about' 
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'search_friends', to: "users#search"
  get 'search_articles', to: "articles#search"
  post 'add_friend', to: "users#add_friend"
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
  resources :articles do 
    resources :comments
    member do
      post 'like'
    end
  end
  resources :users, except: [:new]
  resources :friendships
end

app/models/article.rb
class Article < ActiveRecord::Base
   has_many :article_categories
   has_many :categories, through: :article_categories
   belongs_to :user
   has_many :likes
   has_many :comments, :dependent => :destroy 
   validates :title, presence:true, length: {minimum: 3, maximum: 50}
   validates :description, presence:true, length: {minimum: 10, maximum: 300}
   validates :user_id, presence: true
   default_scope -> {order(updated_at: :desc)}
   mount_uploader :picture, PictureUploader
   validate :picture_size
    def self.search(param)
        return Article.none if param.blank?
        param.strip!
        param.downcase!
        (title_matches(param)).uniq
    end
    def self.title_matches(param)
        matches('title', param)
    end
    def self.matches(field_name, param)
        where("lower(#{field_name}) like ?", "%#{param}%")
    end
    def thumbs_up_total
       self.likes.where(like: true).size 
    end
    def thumbs_down_total
        self.likes.where(like: false).size
    end
    
    private
        def picture_size
           if picture.size > 5.megabytes
               errors.add(:picture, "should be liss than 5MB")
           end
        end
    
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except:[:index, :show]
    before_action :require_same_user, only:[:edit, :update, :destroy]
    
    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @article = Article.new
    end
    def edit
    end
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfully created"
           redirect_to article_path(@article) 
        else
            render 'new'
        end
    end
    
    def update
        if @article.update(article_params)
            flash[:success] = "Article was successgully updated"
            redirect_to article_path(@article)
            
        else
            render 'new'
        end
    end
    
    def show
    end
    
    def destroy
       @article.destroy
       flash[:danger] = "Article was successfully deleted"
       redirect_to articles_path
    end
    
    def search
      @articles = Article.search(params[:search_param]) 
      if @articles
         render 'articles/showFind'
      else
          render status :not_found, nothing: true
      end
    end
    def like
        @article = Article.find(params[:id])
        like_hold = Like.create(like: params[:like],user: current_user, article: @article)
        if like_hold.valid?
            flash[:success] = "Your selection was successful"
            redirect_to :back
        else
            flash[:danger] = "Can only select once"
            redirect_to :back
        end
    end
   
    private
    def set_article
        @article = Article.find(params[:id])
    end
    def article_params
        params.require(:article).permit(:title, :description, :picture, category_ids: [])
    end
    def require_same_user
       if current_user != @article.user and !current_user.admin?
           flash[:danger] = "You can only edit your own articles"
           redirect_to root_path
       end
    end
end

app/views/articles/_article.html.erb
<body class="body">
 <% op.each do |article| %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>
                <div class="article-body">
                    <%= truncate(article.description, length: 30) %>
                   </br>
                        <%= image_tag(article.picture.url, size: "250x150", class: "gravatar") if article.picture? %>
                    
                    <div class="article-meta-details">
                    <small>Created by: <%= article.user.username if article.user %>,<%= time_ago_in_words(article.created_at) %> ago, last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                    </div>
                </div>
                <% if article.categories.any? %>
                    <p>Categories: <%= render article.categories %></p>
                <% end %>
                
                <div class="pull-right">
        <%= link_to like_article_path(article, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= article.thumbs_up_total %>
        <% end %>  &nbsp&nbsp&nbsp&nbsp
        <%= link_to like_article_path(article, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i>  &nbsp <%= article.thumbs_down_total %>
        <% end %>
        </div>
                <% if logged_in? && (current_user == article.user || current_user.admin? ) %>
                <div class="article-actions">
                    <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
                    <%= link_to "Delete article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %>
                </div>
                <% end%>
            </div>
        </div>
    </div>
    <% end %>
</body>    

app/views/articles/_form.html.erb
<body class="body">
<%= render 'shared/errors', op: @article %>

<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form", multiport: true}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :title %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of article" %>
            </div>
    </div>
     <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :description %>
            </div>
            <div class="col-sm-8">
                <%= f.text_area :description, rows: 10,class: "form-control", placeholder: "Content of article" %>
            </div>
     </div>
    <div class="form-group">
        <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
        </div>
        </div>
    </div> 
    <span class="picture">
        <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
        Choose an image to upload:
        </br>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        </div>
        </div>
        </br>
    </span>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
    </div>
<% end %>
    <div align="center">
        <%= link_to " Back to categories", articles_path %>
    </div>
    </div>
</div>

<script type="text/javascript">
    $('#article_picture').bind('change',function(){
        size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5){
            alert('Maximum file size is 5MB');
        }
    });
</script>
</body>

app/views/articles/_lookup.html.erb
<div id="article-lookup">
    <h3>Search for articles</h3>
    <%= form_tag search_articles_path, remote: true, method: :get, id: 'article-lookup-form' do %>
    <div class="form-group row no-padding text-center col-md-12">
        <div class="col-md-10">
            <%= text_field_tag :search_param,
                params[:search_param],
                placeholder: 'Username or Email',
                autofocus: true,
                class: 'form-control search-box input-lg' %>
        </div>
        <div class="col-md-2">
            <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
                <i class='fa fa-search'></i> Look up a article
            <% end %>
        </div>
    </div>
    <% end %>
    <%= render 'common/spinner' %>
    <% if @users %>
    <% if @users.size > 0 %>
    <h3>Search Results</h3>
    <div id="article-lookup-results" class="well results-block col-md-12">
        <table class="search-results-table col-md-12">
        <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><strong>Name:</strong> <%= user.username %></td>
            <td><strong>Email:</strong> <%= user.email %></td>
            <td><strong>Profile:</strong> <%= link_to "View Profile", user_path(user), class: "btn btn-xs" %>
            <% if current_user.not_articles_with?(user.id) %>
                <%= link_to "Add as my article", add_article_path(user: current_user, article: user),
                class: 'btn btn-xs btn-primary', method: :post %>
             <% else %>
                <span class='label label-primary'>
                You are articles
                </span>
                
            <% end %>
            </td>
        </tr>
        <% end %>
        </tbody>
        </table>
    </div>
    <% else %>
        <p class="lead col-md-12">
            No people match this search criteria
        </p>
    <% end %>
<% end %>
<div id="article-lookup-errors"></div>
</div>

app/views/articles/index.html.erb
<h1 align="center">All articles</h1>
<div align="center" >
    <%= will_paginate %>
</div>
<%= render 'article', op: @articles %>
<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/show.html.erb
<body class="body">
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <div class="comment-body">
    <% if @article.user %>
    <ul class="listing">
                <div class="row center">
                    <div class="col-md-4 col-md-offset-4">
                        <li>Created by:</li>
                        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                        <li class="article-title">
                            <%= link_to @article.user.username, user_path(@article.user) %>
                        </li>
                        <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
                    </div>
                </div>
    </ul>
    <% end %>
    <h4 class="descript"><strong>Description:</strong></h4>
    <%= simple_format(@article.description) %>
    <div class="show_article">
        <%= image_tag(@article.picture.url, :height => "50%", class: "gravatar") if @article.picture? %>
    </div>
    <div class="pull-right">
        <%= link_to like_article_path(@article, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @article.thumbs_up_total %>
        <% end %>  &nbsp&nbsp&nbsp&nbsp
        <%= link_to like_article_path(@article, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i>  &nbsp <%= @article.thumbs_down_total %>
        <% end %>
    </div>
    </div>
    <% if @article.categories.any? %>
        <p>Categories: <%= render @article.categories %></p>
    <% end %>
    
    <% if @article.comments.any? %>
    <div class="comment-actions">
    <h4><strong>Comments:</strong></h4>
    </div>
    <% end %>
    <% @article.comments.each do |comment| %>
      <div>
      <p>
        <b><%= gravatar_for(comment.user) %> <%= link_to comment.user.username, user_path(comment.user) %>: </b>
        <%= comment.body %>
        <% if logged_in? && (current_user == comment.user || current_user.admin?) %>
        <%= link_to 'x', [comment.article, comment], :confirm => 'Are you sure?', :method => :delete , class:"close" %>
        <% end %>
      </p>
      </div>
    <% end %>
    <%  if logged_in? %>
    <h4><strong>Add a comment:</strong></h4>
        <%= form_for([@article, @article.comments.build]) do |f| %>
          <div class="col-sm-12">
            <%= f.text_field :body, class:"form-control" ,id:"inputEmail3" ,placeholder:"Comment"%>
          </div>
        <% end %>  
    <br><br>    
    <% end %>
    <div class="article-actions">
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
        <%= link_to "Delete article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %>
        <% end %>
        <%= link_to "Back to articles", articles_path, class: "btn btn-xs btn-success" %>
    </div>
</div>
</body>

app/views/articles/showFind.html.erb
<body class="body">
<h3>Search Results</h3>
        <% if @articles %>
        <% if @articles.size > 0 %>
        <% @articles.each do |article| %>
            <div class="row">
                <div class="col-xs-8 col-xs-offset-2">
                    <div class="well well-lg">
                        <div class="article-title">
                            <%= link_to article.title, article_path(article) %>
                        </div>
                        <div class="article-body">
                            <%= truncate(article.description, length: 30) %>
                        <div class="article-meta-details">
                            <small>Created by: <%= article.user.username if article.user %>,<%= time_ago_in_words(article.created_at) %> ago, last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                        </div>
                    </div>
                    <% if article.categories.any? %>
                        <p>Categories: <%= render article.categories %></p>
                    <% end %>
                    <% if logged_in? && (current_user == article.user || current_user.admin? ) %>
                    <div class="article-actions">
                        <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
                        <%= link_to "Delete article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %>
                    </div>
                    <% end%>
                    </div>
                </div>
            </div>
        <% end %>
        <% else %>
            <p class="lead col-md-12">
                No article match this search criteria
            </p>
        <% end %>
    <% end %>
    </div>
    </body>