config/routes.rb
Rails.application.routes.draw do
  resources :images
  root 'pages#home'
  get 'friends', to: "users#friends"
  get 'arthour', to: 'pages#arthour'
  get 'about', to: 'pages#about' 
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'search_friends', to: "users#search"
  get 'search_articles', to: "articles#search"
  post 'add_friend', to: "users#add_friend"
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
  resources :articles do 
    resources :comments
    member do
      post 'like'
    end
  end
  resources :users, except: [:new]
  resources :friendships
end

app/views/layouts/_footer.html.erb
<div class = "container">
    <footer class="footer">
        <small>
            Copyright &copy; <a><%= link_to "Henry Lu", arthour_path %></a>,<a><%= link_to "  Jeff Lu", arthour_path %></a>,<a><%= link_to "  Jason Wang", arthour_path %></a>
        </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
        </ul>
    </nav>
     </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Study Web", root_path, class: "navbar-brand", id: "brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path, id:"s_top" %></li>
        <li><%= link_to "View Users", users_path, id: "ddd" %></li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" id="ms" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" color="white">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article", new_article_path %></li>
            <li><%= link_to "My Friends", friends_path %></li>
          </ul>
        </li>
        <% end %>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="CA">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li role="separator" class="divider"></li>
          <li><%= link_to "All Categories", categories_path %></li>
          <li role="separator" class="divider"></li>
          <% Category.all.each do |category| %>
            <li><%= link_to "#{category.name}", category_path(category) %></li>
          <% end %>
          <% if logged_in? and current_user.admin? %>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Create New Category", new_category_path %></li>
          <% end %>
        </ul>
      </li>
      </ul>
      <%= form_tag search_articles_path, remote: true, method: :get, 
          id: 'article-lookup-form',class: "navbar-form navbar-left" do %>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group" id="article-lookup">
          <%= text_field_tag :search_param,
                params[:search_param],
                placeholder: 'article title',
                autofocus: true,
                class: 'form-control search-box' %>
        </div>
        <%= button_tag(type: :submit, class: 'btn btn-default') do %>
           <i class='fa fa-search'></i> Search article
        <% end %>
      </form>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to 'Log out', logout_path, method: :delete,id: "mynn" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="hello"><%= current_user.username %>'s profile <%= "(Admin)" if current_user.admin? %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit profile", edit_user_path(current_user)%></li>
            <li><%= link_to "View your profile", user_path(current_user) %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to 'Log in', login_path, id: "mynn" %></li>
          <li><%= link_to 'Sign Up', signup_path,id: "myn" %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>